"""crear_tablas_iniciales

Revision ID: 16f249214180
Revises: 
Create Date: 2026-04-26 20:20:35.083317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16f249214180'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cognito_sub', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.Column('rol', sa.Enum('admin', 'operador', 'visor', name='rolenum'), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cognito_sub'),
    sa.UniqueConstraint('email')
    )
    op.create_table('documentos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('titulo', sa.String(), nullable=False),
    sa.Column('url_fuente', sa.String(), nullable=False),
    sa.Column('jerarquia', sa.Integer(), nullable=False),
    sa.Column('estado', sa.Enum('pendiente_aprobacion', 'indexado', 'archivado', name='estadodocumentoenum'), nullable=False),
    sa.Column('subido_por', sa.UUID(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['subido_por'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('historial_chat',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('documento_id', sa.UUID(), nullable=True),
    sa.Column('pregunta', sa.Text(), nullable=False),
    sa.Column('respuesta', sa.Text(), nullable=False),
    sa.Column('puntaje_confianza', sa.Float(), nullable=False),
    sa.Column('es_fallback', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['documento_id'], ['documentos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reportes_feedback',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('historial_id', sa.UUID(), nullable=False),
    sa.Column('es_correcto', sa.Boolean(), nullable=False),
    sa.Column('comentario', sa.Text(), nullable=True),
    sa.Column('estado', sa.Enum('abierto', 'resuelto', name='estadofeedbackenum'), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['historial_id'], ['historial_chat.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reportes_feedback')
    op.drop_table('historial_chat')
    op.drop_table('documentos')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
