"""agregar_categoria_dependencia_documento

Revision ID: 6673e904a003
Revises: 16f249214180
Create Date: 2026-04-26 22:21:22.656947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6673e904a003'
down_revision: Union[str, Sequence[str], None] = '16f249214180'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documentos', sa.Column('categoria', sa.String(), nullable=True))
    op.add_column('documentos', sa.Column('dependencia', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documentos', 'dependencia')
    op.drop_column('documentos', 'categoria')
    # ### end Alembic commands ###
