"""add documento metadata fields

Revision ID: 9b73f01a0cc7
Revises: s7t8u9v0w1x2
Create Date: 2026-05-27 23:42:29.141447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b73f01a0cc7'
down_revision: Union[str, Sequence[str], None] = 's7t8u9v0w1x2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_audit_log_accion', table_name='audit_log')
    op.drop_index('ix_audit_log_creado_en', table_name='audit_log')
    op.alter_column('consultas_invitado', 'puntaje_confianza',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.add_column('documentos', sa.Column('descripcion', sa.Text(), nullable=True))
    op.add_column('documentos', sa.Column('anio', sa.Integer(), nullable=True))
    op.add_column('documentos', sa.Column('nro_resolucion', sa.String(), nullable=True))
    op.add_column('documentos', sa.Column('nro_decreto', sa.String(), nullable=True))
    op.add_column('documentos', sa.Column('autor', sa.String(), nullable=True))
    op.alter_column('memoria_usuario', 'total_consultas',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('uq_perfil_seccion', 'perfil_permisos', type_='unique')
    op.drop_constraint('uq_permiso_usuario_seccion', 'permisos_usuario', type_='unique')
    op.alter_column('urls_oficiales', 'activa',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('validaciones_respuesta', 'puntaje_confianza',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('validaciones_respuesta', 'fuente',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('validaciones_respuesta', 'estado',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('validaciones_respuesta', 'estado',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('validaciones_respuesta', 'fuente',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('validaciones_respuesta', 'puntaje_confianza',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('urls_oficiales', 'activa',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.create_unique_constraint('uq_permiso_usuario_seccion', 'permisos_usuario', ['usuario_id', 'seccion'])
    op.create_unique_constraint('uq_perfil_seccion', 'perfil_permisos', ['perfil_id', 'seccion'])
    op.alter_column('memoria_usuario', 'total_consultas',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('documentos', 'autor')
    op.drop_column('documentos', 'nro_decreto')
    op.drop_column('documentos', 'nro_resolucion')
    op.drop_column('documentos', 'anio')
    op.drop_column('documentos', 'descripcion')
    op.alter_column('consultas_invitado', 'puntaje_confianza',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.create_index('ix_audit_log_creado_en', 'audit_log', ['creado_en'], unique=False)
    op.create_index('ix_audit_log_accion', 'audit_log', ['accion'], unique=False)
    # ### end Alembic commands ###
